// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY0zfaFIE52REJOi-Govg1ZHu5EPvY_Vo',
    appId: '1:505880735220:android:52cd4b06b4771437461da1',
    messagingSenderId: '505880735220',
    projectId: 'ezcharge-7e845',
    databaseURL:
        'https://ezcharge-7e845-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ezcharge-7e845.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPwOEr4t72pNVn9a1oHe7yjGMK0KkXy1A',
    appId: '1:505880735220:ios:14f7895c7ff311e2461da1',
    messagingSenderId: '505880735220',
    projectId: 'ezcharge-7e845',
    databaseURL:
        'https://ezcharge-7e845-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ezcharge-7e845.firebasestorage.app',
    androidClientId:
        '505880735220-g5tfbuqeglanfm8h6mem3cu592ohup47.apps.googleusercontent.com',
    iosClientId:
        '505880735220-ntk675qrudi24u634583sfjnvoukgfqn.apps.googleusercontent.com',
    iosBundleId: 'com.xujack.ezcharge',
  );
}
